[package]
name = "fibonacci-32-script"
version = "1.1.0"
edition = "2021"
publish = false

[dependencies]
sp1-sdk = { workspace = true }
sp1-zkvm = { workspace = true }

[build-dependencies]
sp1-build = { workspace = true }